apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: minimal-spring-web-demo
  namespace: my-images
  labels: null
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Image","apiVersion":"kpack.io/v1alpha1","metadata":{"name":"minimal-spring-web-demo","namespace":"my-images","creationTimestamp":null},"spec":{"tag":"benjvi/minimal-spring-web-demo","builder":{"kind":"Builder","namespace":"my-images","name":"default"},"serviceAccount":"default","source":{"git":{"url":"https://github.com/benjvi/minimal-spring-web-demo","revision":"main"}},"build":{"resources":{}}},"status":{}}'
spec:
  build:
    resources: {}
  builder:
    kind: Builder
    name: default
    namespace: my-images
  cacheSize: 2G
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccount: default
  source:
    git:
      revision: main
      url: https://github.com/benjvi/minimal-spring-web-demo
  successBuildHistoryLimit: 10
  tag: benjvi/minimal-spring-web-demo
