apiVersion: v1
kind: Service
metadata:
  name: minimal-spring-demo
  labels:
    run: minimal-spring-demo
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: minimal-spring-demo
  sessionAffinity: None
  type: LoadBalancer
