name: Deploy via GitOps

on:
  schedule:    
  - cron: "0 10 * * *"
  push:
    branches:
    - main
  repository_dispatch:
    types:
      - "manual-deploy" 

jobs:
  pipeline:
    environment: default
    env:
      APPS_GITOPS_GIT_DEPLOY_KEY: ${{ secrets.APPS_GITOPS_GIT_DEPLOY_KEY }}
    runs-on:
    - ubuntu-latest
    steps:
      - name: Triggered by event
        if: github.event_name == 'repository_dispatch'
        run: 'echo "Triggered by: ${{ github.event.client_payload.user }}"'

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run tests
        uses: docker://maven:latest
        with:
          args: 'test'

      - name: Get published docker image
        with:
          entrypoint: '.github/scripts/tbs-get-image-version.sh'
        uses: docker://benjvi/kp:latest
        env:
          KUBECONFIG_CONTENT: ${{ secrets.TBS_KUBECONFIG }}

      - name: Deploy manifests
        with:
          entrypoint: '.github/scripts/gitops-deploy.sh'
        uses: docker://benjvi/prify:latest
